<?php
return array(
		'Overview' => '概览',
		'Articles' => '文章总数',
		'Drafts' => '草稿',
		'Trash' => '回收站',
		'Comments' => '评论总数',
		'System' => '系统',
		'Server' => '服务器',
		'Software' => '软件',
		'Database' => '数据库',
		'Latest Articles' => '最新文章',
		'Latest Comments' => '最新评论',
		
		'Title' => '网站名称',
		'Keywords' => '关键字',
		'Description' => '网站描述',
		'Theme' => '主题',
		'Language' => '语言',
		'Time Zone' => '时区',
		'Temporary files' => '临时文件',
		'Clear' => '清 除',
		'Clear temporary files generated by the release articles.' => '清除由发布文章所产生的临时文件。',
		'Cache' => '缓存',
		'Refresh' => '刷 新',
		'Refresh the page cache, usually after the release of the article to use.' => '刷新页面缓存，通常在发布文章后使用。',
		
		'Turn off caching' => '关闭缓存',
		'15 minutes' => '15 分钟',
		'1 hour' => '1 小时',
		'4 hours' => '4 小时',
		'1 day' => '1 天',
		'7 days' => '7 天',
		
		'Site settings have been updated!' => '网站设置已更新！'
);